### ISSUE TITLE
Shorten vignettes name

### ISSUE THREAD

**Issue by brunj7** [lter/lterdatasampler#1]
The vignette names are too long to look good on the website.

2 options:
- shorten the title to the vignette to theme + site, e.g. Lake Ice Cover -- NTL, and add a subtitle
- modify the `pkgdown` yaml file to overwrite the vignette's name 

Let me know if you have a preference @allisonhorst !

**Comment by allisonhorst** [comment]
Yeah I agree - shorter but also it'd be great to avoid abbreviations on the actual vignette title, so maybe something like "North Temperate Lakes Ice Cover" or something?

**Comment by brunj7** [comment]
We need to keep the 3 letters acronym to link with the data, so maybe `North Temperate Lakes Ice Cover (NTL)`?

**Comment by allisonhorst** [comment]
> We need to keep the 3 letters acronym to link with the data, so maybe `North Temperate Lakes Ice Cover (NTL)`?

Yeah that sounds great to me

**Comment by brunj7** [comment]
I added subtitle for NTL and the PIE acronym to the crab vignette. I think it is looking good now

**Comment by brunj7** [comment]
applied the same approach to other datasets
