### ISSUE TITLE
Add dataset #2

### ISSUE THREAD

**Issue by brunj7** [lter/lterdatasampler#2]
We need to select the second dataset to showcase

Capstone repo: https://github.com/ucsb-ds-capstone-2021/lterdatasets

**Comment by allisonhorst** [comment]
Added the crab-latitude (PIE) dataset, pushed to `ah-branch` for review & merge if it looks good

**Comment by brunj7** [comment]
Looking good! I merged it into the main branch and added the data sample reference to the README
