### ISSUE TITLE
Reach out to IM Managers

### ISSUE THREAD

**Issue by allisonhorst** [lter/lterdatasampler#27]
- [x] KNZ - Konza Prairie Bison (Allison)
- [x] AND - Andrews Vertebrates (Allison)
- [x] HUB - Hubbard Brooks Sugar Maples (Allison)
- [x] PIE - Plum Island Ecosystem (Julien)
- [x] NWT - Niwot Pikas (Julien)
- [x] NTL - North Temperate Lakes Icecover (Julien)

**Comment by brunj7** [comment]
Updates:

- KNZ:  Yang sent us quotes and pictures and said vignette content looked ok
- HBS:  So far very positive feedback. JB sent a follow-up to gather more info.

**Comment by brunj7** [comment]
- NTL: followed up quickly, but asking more time to review
- NWT: Just sent

**Comment by brunj7** [comment]
NWT feedback has been implemented (#51, #52, #53) and sent back to Ashley and Chris

**Comment by brunj7** [comment]
I think we did all the above listed requests
