### ISSUE TITLE
Add dataset #3

### ISSUE THREAD

**Issue by brunj7** [lter/lterdatasampler#3]
Need to select and add our dataset #3

Capstone repo: https://github.com/ucsb-ds-capstone-2021/lterdatasets

**Comment by brunj7** [comment]
Creating the `hbr-mapple` branch to import the student data and vignette

**Comment by brunj7** [comment]
- Added the original data and vignette
- Updated the README
- Added broom example (tidy)
- Added more explanations

Maybe adding linear regression on groups?

**Comment by allisonhorst** [comment]
Ah bummer I didn't see that you had already done this, sorry. Anyway pushed a branch with some edits in it, not sure if it's worth merging those in your just using your version (you'll probably want to reject my merge) but maybe worth looking at to see how our examples & edits align

**Comment by allisonhorst** [comment]
>     * Added the original data and vignette
> 
>     * Updated the README
> 
>     * Added broom example (tidy)
> 
>     * Added more explanations
> 
> 
> Maybe adding linear regression on groups?

- I think adding a `broom::tidy()` example is a great idea for the t-test output. 
- I don't think we need to actually do the regression here, just showing the graphs is good enough

**Comment by brunj7** [comment]
merged your version and updated with broom example and header level.
