### ISSUE TITLE
Draft blog announcement

### ISSUE THREAD

**Issue by allisonhorst** [lter/lterdatasampler#56]

**Comment by brunj7** [comment]
Here is the first draft: https://docs.google.com/document/d/14dgYLW_6RfuSAbZN1TzLjRgXXjljUdoJCRck8jes078/edit#

**Comment by brunj7** [comment]
Live: https://lternet.edu/stories/ready-to-teach-r-environmental-datasets-the-lterdatasampler-r-package/
