### ISSUE TITLE
Number of variables for and_vertebrates

### ISSUE THREAD

**Issue by marierivers** [lter/lterdatasampler#77]
The Format section of the and_vertebrates_doc page states that the data has 6 variables while it actually has 16 variables.
https://lter.github.io/lterdatasampler/reference/and_vertebrates.html

**Comment by brunj7** [comment]
HI @marierivers ,

Thank you for catching this! We will work shortly on fixing this.

**Comment by allisonhorst** [comment]
Thanks again Marie! We've updated :)
